apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: avshalomts/backend:latest
          ports:
            - containerPort: 3000
          # env:
          #   - name: DATABASE_URL
          #     value: postgres://youruser:yourpassword@postgres:5432/yourdb
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
